INSERT INTO TB_USER (OBJID,USERNAME, PASSWORD, ROLES) VALUES (1,'admin', '123', 'ROLE_ADMIN');
INSERT INTO TB_USER (OBJID,USERNAME, PASSWORD, ROLES) VALUES (2,'ihundan', '123', 'ROLE_USER');
INSERT INTO TB_USER (OBJID,USERNAME, PASSWORD, ROLES) VALUES (3,'wukonglin', '123', 'ROLE_ADMIN,ROLE_USER');
INSERT INTO TB_USER (OBJID,USERNAME, PASSWORD, ROLES) VALUES (4,'other', '123', 'ROLE_OTHER');
